canonical/uss-tableflip

- scripts/cla-query
Added handy script used to query if a lpid has signed the CLA
> Add scripts/cla-query

- scripts/review-mps
This assists writing a jenkins job to perform this task
> github: add merge-url param to allow providing a specific MP to merge

- doc/ctool.md
- scripts/ctool
Just walk through some interactions with ctool to show its usefulness.
> doc: Add documentation/demo about ctool

- scripts/new-upstream-snapshot
> Fix `new-upstream-release -h`

- doc/upstream_release_process.md
- scripts/upstream-release
Error if not on master or unable to git pull master.
> tools: upstream-release checkout master before creating changelog

- doc/ubuntu_release_process.md
doc update given that we now should be refreshing quilt patched only in the ubuntu/daily/$release branches.
Related PR where this procedure is used https://github.com/canonical/cloud-init/pull/435
> docs: update ubuntu quilt refresh procedure for ubuntu/daily/$release

- scripts/build-package
*  Fix additional space in error/debug message.
*  Support package versions with an epoch.
*  Native and non-native package build improvements.
> 2 small changes and 1 large

- scripts/get-orig-tarball
Add this script from smoser's gists, which downloads
an orig tarball.  
Originally at https://gist.github.com/smoser/fa77f61a2b650d115b5fc2a8ab028ede
> add get-orig-tarball

- scripts/log2dch
to test:
git clone https://github.com/canonical/cloud-init.git
cd cloud-init
git checkout origin/ubuntu/xenial
git log diff ubuntu/20.2-45-g5f7825e2-0ubuntu1_16.04.1..HEAD | log2dch --trello
> log2dch: update --trello output to link github PRs

- scripts/cla-query
- scripts/lp-attach-file
- scripts/sru-changelog-format
Scripts:
cla-query
lp-attach-file
sru-changelog-format
> Update to Python 3 and cleanup three more scripts

- doc/new-ubuntu-series.md
I separated cloud-init and curtin as the projects are now managed by
different teams.
> Update the new-ubuntu-series doc

- doc/ubuntu_release_process.md
just some scrubbing on latest release attempt into Impish
> release doc update

- doc/ubuntu_release_process.md
Since we recently add --first-devel-upload param to new-upstream-snapshot
> doc: ubuntu_release_doc include --first-devel-upload info

- doc/new-ubuntu-series.md
Minor doc updates for build recipes when new ubuntu series is released.
> docs: new-ubuntu-series minor recipe updates

- .pre-commit-config.yaml
- scripts/cla-query
- scripts/jenkins-get-job
- scripts/lp-attach-file
- scripts/lp-bugs-released
- scripts/lp-create-bug
- scripts/package-sponsor
- scripts/review-mps
- scripts/sru-changelog-format
- scripts/tboard.py
Add optional pre-commit config to clean any commits.
If pre-commit is installed run the following per commit:
- flake8
- isort
- black
To install pre-commit in your working directory:
pip3 install pre-commit
pre-commit install
To test:
pre-commit run --all-files
> pre-commit: .pre-commit-config.yaml to keep things tidy

- scripts/add_changelog.py
Fix new-upstream-snapshot to avoid injecting headers above each
changelog entry like:
[ Author Name ]
- some commit summary
Also fix whitespace alignment on indented split lines due to
line wrap.
```
cd /tmp
git clone git@github.com:canonical/cloud-init.git
cd cloud-init 
git checkout upstream/ubuntu/devel -B ubuntu/devel
new-upstream-snapshot
```
* Without this PR, the absence of --nomultimain creates a changelog entry that will have Authorship headers before each commit.
* With this PR, ensure changelog format follows the same conventions for changelog entries as in past releases
> gbp: avoid dch authorship headers setting --nomultimaint

- scripts/gbp_format_changelog
gbp_format_changelog: Filter alberto
> gbp_format_changelog: Filter alberto

- doc/ubuntu_release_process.md
docs: ubuntu_release_process fix minimum Ubuntu
> docs: ubuntu_release_process fix minimum Ubuntu

- scripts/new_upstream_snapshot.py
Example of most recent log generated:
```
cloud-init (23.4.1-0ubuntu1~22.04.3) UNRELEASED; urgency=medium
* d/cloud-init.maintscript: remove /etc/cloud/clean.d/README
* d/cloud-init.logrotate: add logrotate config for cloud-init
* refresh patches:
- d/p/retain-netplan-world-readable.patch
- d/p/status-do-not-remove-duplicated-data.patch
- d/p/status-retain-recoverable-error-exit-code.patch
* Upstream snapshot based on upstream/main at 33148a07.
```
> Add quilt patch refresh to debian changelog

- scripts/new_upstream_snapshot.py
Without this fix we see the following:
```
Running: git merge upstream/main -m "merge from upstream/main at 23.4-174-g160b5ac8"
Dropping any cpicks that we've pulled in from main
Attempting to automatically refresh quilt patches
No series file found
No series file found
'quilt pop -a' unexpectedly returned 1.
```
when no series file exists
> fix: Don't break when no patches exist

- scripts/cherry-pick
See https://chat.canonical.com/canonical/pl/u19ie4q5wjyeug7pdgmruagotc
> Add DEP-3 message to cherry-pick script

- scripts/upstream-release
also fixing some minor bashisms in the area
> Include github issues in the total issues list
