- scripts/ctool
I noticed that the http_proxy settings were not getting passed through
to apt-get (run-container --install=package1), and thus the proxy
not getting used.  This was due to the apt_get function invoking
sudo.  That was not necessary as the 'install_packages' function
already ensured that it was running as root (--user=root).
So.. the easy fix is to just *not* use sudo.  It uses env instead so
that the debug statement can represent that environment var was used.
> Do not lose proxy settings when invoking apt.

- scripts/build-package
If not provided with any arguments, build-package would build a source
package using '-d' (no-check-builddeps).
The change here is just to add '-nc' as well.
Without this change, the clean target will be invoked and may fail
if that target used a missing builddep.
The invocation of debuild is done in a clean git worktree in a
temporary directory, so there is no need to clean first.
> build-package: default to debuild with -nc.

- scripts/ctool
If adding a user to a container failed, it would not show the
correct container name.
> ctool: fix typo in variable name in a error message.

- scripts/ctool
Since LXD version 3.17 the lxc command is able to read the container
configuration as YAML from stdin on `lxc init` and `lxc launch`. This
broke the ctool script, which is supposed to take a script from stdin,
but stdin is now consumed by lxc. To avoid this this commit adds a
</dev/null when running `lxc launch`.
> ctool: launch containers with 'lxc launch ... </dev/null'

- scripts/review-mps
To allow cloud-init to merge approved branches from Launchpad
into github upstream, we can specify a --push-remote like
git@github.com:canonical/cloud-init.
This nos allow us to merge LP branches directly into github upstream
and mark those branches as merged in LP.
Also adapt out bug and branch comments to point at the upstream github
repo instead of locally at launchpad commitish URLs.
> review-mps: allow passing a github url to --push-remote

- scripts/review-mps
Now review-mps clones github.com/canonical/cloud-init as origin and handle remote merge setup for LP users.
> github: change review-mps upstream to github

- scripts/ctool
Given a git url, ctool clones the repository to a target directory named
as the url with everything up the last '/' removed, so:
https://github.com/user/repo is cloned to 'repo'
lp:~user/repo is cloned to 'repo'
This doesn't work when the url doesn't contain a '/', something that can
happen when using the 'lp:' shorthand, e.g.
lp:project is cloned to 'lp:project'
This happens to break the virtualenv Python module in some test
environments because of [1]. This commit constructs the `git clone` target
directory first by trimming the git url up to the first ':', and then
up to the last '/', accounting for 'slashless' URLs.
[1] https://github.com/pypa/virtualenv/issues/395
> ctool: ensure there are no colons in the 'git clone' target directory

- scripts/ctool
If you do not want to give the user password-less sudo, then
you can use the --no-sudo flag.
ctool add-user --no-sudo bobby
> ctool add-user: add --no-sudo option.

- scripts/ctool
This makes ctool do the right thing for add-user if user is not root.
$ ctool add-user -v testsm1
adding user testsm1
$ sudo `which ctool` add-user -v testsm2
adding user testsm2
$ ctool add-user -v --container=b1 testb1sm1
[b1] adding user testb1sm1
$ ctool execute --user=testsm2 -- sh -c 'whoami; pwd'
testsm2
/home/testsm2
$ ctool execute --container=b1 --user=testb1sm1 -- sh -c 'whoami; pwd'
testb1sm1
/home/testb1sm1
> Fix add-user to work without --container.

- scripts/log2dch
- scripts/new-upstream-snapshot
* Add a FILTER_LIST to log2dch to redact matching commits from changelog
* Add --skip-bugs param to log2dch so that it new-upstream-snapshot can use it
* Remove function duplication in new-upstream-snapshot to use log2dch
> log2dch: redact and lp-to-git-users from debian changelog

- scripts/jenkins-get-job
MAAS jenkins requires username and password.
This branch is used in SRU testing to havest logs from the MAAS server by: https://github.com/cloud-init/ubuntu-sru/pull/77
> scripts: jenkins-get-job accepts username/password for MAAS jenkins

- scripts/lp-create-bug
Add a script to assist in creating bulk bugs from the command line for bitesized tasks that the
cloud-init/curtin community can field.
To create a triaged, low-weight bug in cloud-init project with the bitesize tag:
cat > bug-descr  <<EOF
Here is my test bug description
EOF
lp-create-bug cloud-init --status Triaged --importance Low --title "test bug: please ignore/delete" --description @bug-descr
> scripts: add lp-create-bug script for bulk bug creation from files

- scripts/log2dch
UA Client doesn't squash merge, filter our Merge commit markers from log2dch output
> log2dch: filter out github Merge marker commits

- scripts/new-upstream-snapshot
Providing --skip-release param to new-upstream-snapshot will:
- update quilt patches if needed
- merge all  upstream commits and document them in debian/changelog
- leave SRU_BUG_NUMBER_HERE marker and UNRELEASED state in most recent
debian/changelog entry
Also, new-upstream-snapshot will now combine the current commits listed in
debian/changelog 'New upstream snapshot' section if the unreleased changelog
entry also contains a 'New upstream snapshot' section.
To test:
```
cd /tmp;
git clone git@github.com:canonical/cloud-init.git
cd cloud-init
git checkout -b ubuntu/bionic origin/ubuntu/bionic
new-upstream-snapshot --skip-release
```
> tools: new-upstream-snapshot accept --skip-release param

- doc/ubuntu_release_process.md
Document process for updating/fixing daily PPA recipe builds, specifically
how to fix up the ua revert patches on xenial and bionic.
Also, remove trailing whitespace on a few lines.
> Document fixing ua revert patch

- scripts/new-upstream-snapshot
When merging  ssh-import-id from master at 5.8 to the ubuntu/debian
branch, it would cause merge conflict due to upstream maintaining a
debian/changelog.
The "fix merge commit" shell basically worked as designed, but
then when exiting the shell the 'git show --format=%P' would have changes.
We really just wanted to get the parent commits, not show diffs.
So... the fix is to just use '--no-patch'
> new-upstream-snapshot: fix 'is_merge_commit'

- doc/upstream_release_process.md
- scripts/upstream-release
Because we have branch protection enabled in GitHub, we can't tag the release commit locally before the PR has been squash merged (thereby creating a _new_ release commit). This reflects the changes required to the process.
> Update docs/script for GitHub release process

- doc/ubuntu_release_process.md
Re-reading the document I couldn't remember where the hash came from.
Document the hash of the ua refactor, and then in the commands use
git's ^ to specify the commit *before* the refactor.
> ubuntu_release_process: document the git hash used to revert ua refactor

- doc/ubuntu_release_process.md
It seems there is a typo in the `ubuntu_release_process` doc.
> Fix typo on ubuntu_release_process doc

- doc/ubuntu_release_process.md
- scripts/new-upstream-snapshot
new-upstream-snapshot drops both debian/patches/cpick-* and fix-cpick-* files
because both are considered patches which are already applied in tip of master.
> new-upstream-snapshot: also drop debian/patches/fix-cpick-*

- doc/ubuntu_release_process.md
- scripts/fix-daily-branch
Provide a local source_branch from which to revert all
debian/patches/*cpick*  quilt patches.
This script is performed after each uss-tableflip/scripts/cherry-pick
which added new debian/patches/*cpick* in order to allow build recipe
to merge ubuntu/$release and ubuntu/daily/$release into master before
building a daily package.
To test:
```
cd /tmp
git clone git@github.com:canonical/cloud-init.git
cd cloud-init
git merge origin/ubuntu/focal
git merge origin/ubuntu/daily/focal
fix-daily-branch -s ubuntu/focal -d ubuntu/daily/focal
git checkout master
git reset --hard origin/master
git merge origin/ubuntu/focal
git merge ubuntu/daily/focal
ls debian/patches # expect none
```
> scripts: fix-daily-branch script reverts cpick patches from a source

- scripts/new-upstream-snapshot
usage was incorrect and didn't report --sru-bug as a viable cmdline option.
Also drop unused long_opts
> new-upstream-snapshot: correct usage param docs

- scripts/sbuild-it
This script makes it a bit easier to call sbuild when validating package builds prior to uploading
cloud-init or curtin.
> scripts: add sbuilt-it simple wrapper for sbuild

- scripts/fix-daily-branch
In trying to fix daily recipe builds for ubuntu/xenial  and ubuntu/bionic I noticed that fix-daily-branch did not work because the script tries to revert any commitish from there were no `debian/patches/*cpick*` quilt patches to 'revert' from 
to test:
```
git fetch upstream
git checkout upstream/ubuntu/xenial -B ubuntu/xenial
fix-daily-branch xenial upstream
````
> fix-daily-branch: revert commits on existing debian/patches/*cpick*

- scripts/ctool
The change here allows you to add files to the container before starting
it.  You can then reliably use those programs during boot.  It also
helps to "patch" a container by overwriting a file with a new file.
Syntax is '--push-file=<outside-path>[:<inside-path>]' where
<inside-path> defaults to /usr/local/bin/<basename <outside-path>>.
Put the 'myscript' into /usr/bin under name 'helper':
--push-file=./myscript:/usr/bin/helper
Put 'myscript' into /usr/local/bin:
--push-file=./myscript
> ctool: add --push-file to push files to /usr/local/bin before start.

- scripts/build-package
Per dpkg-source(1) the debian/ directory in the .orig tarball is removed
and replaced with the one from the .debian tarball, so the script is
doing the right thing.
(This is true only for source format 3.0 packages, but build-package
doesn't support non-native 1.0 packages.)
> build-package: drop unneeded "fixme" comment on extracting debian/

- scripts/new-upstream-snapshot
When invoked with --update-patches-only, the code would showed:
if [ -z "$drops" -o -z "$refreshed" ]; then
error "No patches updated. Nothing to commit."
return 0
fi
But really if there are drops *or* refreshes, then we have something
to commit. Negative logic (-z) means we need -a here.
Also, if no changes were made, then we were leaving the merge applied.
Rather, if "update-patches-only" with nothing to do should restore
to the original state.
> new-upstream-snapshot fix bug in --update-patches-only

- scripts/new-upstream-snapshot
if --update-patches had nothing to do, then it would leave the HEAD
set to after the merge.  Rather, if "update-patches-only" with nothing
to do should restore to the original state.
> new-upstream-snapshot --update-patches-only: do nothing if nothing to do

- scripts/log2dch
- scripts/new-upstream-snapshot
- Add a `--first-sru` parameter to `new-upstream-snapshot` to use `distro-info --stable -r` to determine the proper debian version suffix.
- Correct getopt long_opts parsing of `sru-bug:` to require a value
-  log2dch now replaces "LP: #" with  "LP:" in changelog entries when `--skip-bugs` is provided
Fixes: #69
> new-upstream-snapshot: determine proper version suffix on first SRU

- scripts/log2dch
log2dch: redact canonical devs and support github issues as (GH: #\d+)
Redact Lucas and James as upstream cloud-init developers from
debian changelog entries since it is expected that upstream devs will
have the majority of the commits in our projects.
Report (GH #123) in debian changelog entries for repos which use github
issues instead of launchpad bugs by parsing the commit footer containing
either "Fixes: #123" or "Closes: #123"
Also add a new --bug-url parameter to allow overriding default bug links
in trello and markdown output formats.
```bash
git log HEAD^^^^..HEAD | log2dch
```
> log2dch: support github issues with representing (GH: #\d+)

- scripts/fix-daily-branch
Resetting causes discontinuous history.  This tool will handle such
history (because it always resets), but it may cause problems for uses
of the daily branch which this tool does not cover.
Also clean up output a little, to make the messages from the script
easier to identify.
> fix-daily-branch: merge instead of reset

- scripts/sbuild-it
Testable with
```bash
sudo sbuild-launchpad-chroot create \
--architecture="powerpc" "--name=xenial-powerpc" "--series=xenial"
build-package 
sbuilt-id ../*dsc powerpc
```
> sbuild-it: allow specifying option ppcel or riscv64 or powerpc arch

- doc/upstream_release_process.md
A (mostly) rewrite of the upstream release process. Includes every step we had on our trello board and generally includes more details. Selecting `view file` will show the rendered markdown, and might be better than looking at the diff view.
> Update upstream release process (SC-426)

- scripts/upstream-release
Commit messages that include escape sequences get interpreted.
This behavior causes \r\n in the cloud-init changelog to be replaced
by ^M.
> Fix escape sequence bug

- scripts/new-upstream-snapshot
Ensure we grab the devel release information for our first uploads
into a new Ubuntu release.
When uploading to the new devel release use distro-info --devel to
get both series name and version_id which we now use for package
suffix.
Upload into devel release should always contain LP bug ids until that
release is officially published and "stable".
> new-upstream-snapshot: add --first-devel-upload param

- scripts/build-package
- scripts/get-orig-tarball
Packages with an epoch (leading [0-9]:) would fail to build with
build-package or to download the orig tarball with get-orig-tarball.
The crux of the issue was that both tools would leave the epoch
on the upstream version, when it should not be used.
An example that is fixed is pulseaudio.
Before, the following would fail:
get-orig-tarball for --verbose --overwrite pulseaudio \
1:15.0+dfsg1-1ubuntu2.1 .
> Fix build-package and get-orig-tarball for packages with an epoch.

- doc/ubuntu_release_process.md
- Correct typo on fixing daily recipe using --update-patches-only
- Add comment about quilt add for any untracked diffs
- No longer need to reference ubuntu-advantage patches as UA-tools
released full features all the way back to Xenial.
> ubuntu-release-process: correct process for fixing daily build recipe

- scripts/get-orig-tarball
Two things  here actually:
* improvement to --help output of get-orig-tarball
* support downloading things from deb.debian.org in addition
to launchpad.net.
> get-orig-tarball: Add support for downloading from debian.

- scripts/new-upstream-snapshot
```
new-upstream-snapshot: fix devel detection because we add ver suffix
cloud-init now appends a package version suffix even on devel
releases. Fux new-upstream-snapshot to detect if our suffix matches the
current devel release.
```
squash and merge
> new-upstream-snapshot: fix devel detection because we add ver suffix

- scripts/log2dch
ignore non integer `Fixes: SC-##` in commit messages.
Expect github issues to be reprented by a commit message containing
the footer of the formats:
Issue: <GITHUB_ISSUE_NUMBER>
- OR -
Fixes: <GITHUB_ISSUE_NUMBER>
The avoids log2dch reporting (GH: SC-123) for JIRA ticket tracking we do.
Also, allow assume each commit can reference either github issues (GH: #)
or launchpad bug tracker (LP: #) but not both.
This will likely need improved logic in the future.
* Before PR
```bash
cd your-cloud-init-path;
git checkout upstream/main
git log 22.1..HEAD | log2dch | grep GH > BEFORE
cd your-uss-tableflip-path;
git checkout <this_PR>;
cd your-cloud-init-path;
git log 22.1..HEAD | log2dch | grep GH >AFTER
```
> log2dch: do not consider ignore SC-<JIRA> fixes

- doc/upstream_release_process.md
- scripts/add_changelog.py
- scripts/gbp.conf
- scripts/gbp_format_changelog
- scripts/new-upstream-snapshot
```
git-buildpackage provides a utility `gbp dch` which can
git commit summaries directly into debian/changelogs.
This will allow for repo, branch or package specicialization of
changelog formatting override behavior.
By default  no changes are necessary for packaging repositories
which use new-upstream-snapshot.
To override package formatting or gbp-dch defaults in your project,
copy the gbp conf and formatter files into your debian/ directory
and modify as needed:
cp uss-tableflip/scripts/gbp.conf debian/
cp uss-tableflip/scripts/gbp_format_changelog debian/
gbp.* files located in a debian/ local directory will be used
instead of the defaults delivered by uss-tableflip repo.
```
```bash
git checkout upstream/ubuntu/impish -B ubuntu/impish
new-upstream-snapshot
git diff …
```
> new-upstream-snapshot: move toward using gbp-dch

- scripts/new-upstream-snapshot
```
Remove quotes from file list
git commit on a quoted file list was causing failures. Remove them. 
```
Example failure:
```
newt:cloud-init (ubuntu/bionic*) $ git reset --hard eed6d8958b5b0e61c4cf9e476119df20298b598e; new-upstream-snapshot --skip-release
HEAD is now at eed6d8958 update changelog
updating remote upstream for default commitish upstream/main.
Removing patch retain-apt-partner-pocket.patch
Restoring templates/sources.list.ubuntu.tmpl
Removing patch renderer-do-not-prefer-netplan.patch
Restoring tests/unittests/test_render_cloudcfg.py
Restoring config/cloud.cfg.tmpl
Removing patch ec2-dont-apply-full-imds-network-config.patch
Restoring tests/unittests/sources/test_ec2.py
Restoring cloudinit/sources/DataSourceEc2.py
Removing patch openstack-no-network-config.patch
Restoring …
```
> Remove some quotes because bash is a horrible language

- scripts/new-upstream-snapshot
currently a tag in the form XX.X.X is not matched in parsing code in `new-upstream-snapshot` 
```
arc~/cloud-init(ubuntu/devel|…) new-upstream-snapshot 22.3.1     
unrecognized upstream version '22.3.1'
```
this fixes the issue:
```
arc~/cloud-init(ubuntu/devel↓4|…) new-upstream-snapshot 22.3.1
diff --git a/debian/changelog b/debian/changelog
```
> new-upstream-snapshot: support XX.X.X tag format

- doc/upstream_release_process.md
- scripts/upstream-release
Cloud-init is no longer going to create an upstream process bug in Launchpad for upstream cloud-init releases.
> upstream-release: drop upstream launchpad bug (SC-1242)

- scripts/upstream-release
It doesn't actually count domains, just unique emails. We wind up having more domains than contributors, which makes no sense.
> Remove NUM_DOMAINS from upstream release notes

- doc/ubuntu_release_process.md
Add explanation about why performing a new upstream snapshot on ubuntu/<release> branches might conflict with build-package.
> doc/ubuntu_release_process.md: add note

- scripts/build-package
- scripts/get-orig-tarball
- scripts/new_upstream_snapshot.py
*  scripts: build-package try downloading upstream tarfile always
Avoid inconsistencies invalid local orig.tar.gz created by
tools/make-tarball by always attempting to download the latest
match upstream orig.tar.gz file.
If a local orig.tar.gz exists in ../dl, sha256sum it against
upstream's matching version and prompt to use upstream orig.tar.gz
to avoid invalid local orig.tar.gz being used as a debdiff basis.
When no local orig.tar.gz exists, but an upstream orig.tar exists,
use that upstream orig.tar.gz as basis for debdiff creation.
When neither local orig.tar.gz nor upstream orig.tar.gz exists,
allow ./tools/make-tarball to create that local tarfile from CWD.
To accomplish this:
- refactor get-orig-tarfile into a function which will raise
conspicuous messages reporting when upstream …
> Build package fixes

- scripts/new_upstream_snapshot.py
This corrects the suggested dch -R -D UNRELEASED '' comment at end of snapshot.
Also, avoid preferring previous changelog version when quilt patches are updated AND we are snapshotting an annotated upstream tag.
The above avoids using invalid previous suffix .3 etc as we are on a brand new XX.YY SRU so suffix should be ~18.04.1.
```
git checkout upstream/ubuntu/bionic  -B ubuntu/bionic
new_upstream_snapshot.py -c 23.2 -b 2023110
```
```
To release:
dch -r -D bionic ''
git commit -m 'releasing cloud-init version 23.2-0ubuntu0~18.04.1' debian/changelog
git tag ubuntu/23.2-0ubuntu0_18.04.1
```
> new_upstream_snapshot: get previous changelog distro when UNRELEASED

- scripts/build-package
New upstream versioning in devel series for weekly releases will have the version format:
<tag_major_minor>~<release_counter>g<git_hash>
For example, the 2nd weekly release to the ubuntu devel seres after the
upstream annotated tag 23.1 at git commit asdf123 will be:
23.1~2gasdf123
Adapt build-package script to properly determine git hash by redacting the leading 
MM.NN~[0-9]g to determine the upstream hash from which this version was created.
> build-package: handle upstream ver containing ~g<git-hash>

- scripts/build-package
```
New upstream versioning in devel series for weekly releases will
have the version format:
<tag_major_minor>~<release_counter>g<git_hash>
For example, the 2nd weekly release to the ubuntu devel seres after
the annotated tag 23.1 at git commit asdf123 will be:
23.1~2gasdf123
Adapt build-package script to properly determine git hash by
redacting the leading MM.NN~[0-9]g to determine the upstream hash from
which this version was created.
```
> build-package: parse new devel ~#g<git_hash> version format

- scripts/upstream-release
When cloud-init sync's patch-level version into version.py, ensure the replaced version number replaces the previously released full major.minor.patch.
Formerly, upstream-release 23.3 23.2 would generate the diff:
-__VERSION__ = "23.2.2"
+__VERSION__ = "23.3.2"
Version diff is now corrected to represent: `__VERSION__ = "23.3"`
> upstream-release: replace full upstream-release patch version x.y.z

- scripts/new_upstream_snapshot.py
- tests/test_upstream_snapshot.py
See individual commits for their particular changes.
One thing to note that this won't change a current `0ubuntu0`. If our current version numbers have it, we'll need to manually update it once to be correct going forward.
Some of the devel options are now going unused, but that was technically true before. It's just more obvious now. I didn't remove those, as that could come in a separate PR...and we might want to bring them back if we're sure what's supposed to happen.
> New VersionInfo class and ubuntu0->ubuntu1

- scripts/new_upstream_snapshot.py
When new_upstream_snapshot is performed from a commit 24.1 it applies the any new major.minor.patch values from the commit to the previous debian/changelog version. This is done to inherit any ather ubuntu or series-specific suffixes such as ~22.04.1.
This presents a problem when the new upstream tag is only a major.minor and the previos d/changelog version was major.minor.hotfix because the VersionInfo.replace method avoids setting hotfix version if it is None.
Update VersionInfo.replace to honor/set hotfix of None if either major or minor values have changed.
> bug: drop prev d/changelog hotfix when incrementing major/minor

- scripts/log2dch
Upstream git commit messages carry the following footers to represent
an issue is fixed or closed by a cmomit:
Fixes GH-###
Closes GH-###
Allow log2dch to append (GH <id>)  to ChangeLog entry when encountering
such a commit message footer.
> fix(log2dch): track Fixes: GH-<id>  for ChangeLog generation

- scripts/new_upstream_snapshot.py
This will produce smaller diffs by default (after the initial sort).
Also, use a more useful default when no distro-info is available
> sort patches by default
